<a href="https://colab.research.google.com/github/feryamazaki/igtibootcamp/blob/main/trabalhopraticomodulo2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Trabalho Prático do Módulo 2

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Codigo 1
Z = np.zeros((4,))
Z

array([0., 0., 0., 0.])

In [4]:
#Codigo 2
Z = np.zeros((4,))
Z[1] = 1.
Z

array([0., 1., 0., 0.])

In [5]:
#Codigo 3
Z = np.zeros((4,))
Z[1:] = 1.
Z

array([0., 1., 1., 1.])

In [7]:
#Codigo 4
Z = np.zeros((4,))
Z[:-1] = 1.
Z

array([1., 1., 1., 0.])

In [11]:
#Codigo 5
X = np.zeros((2,2))
X[:] = 2.
X

array([[2., 2.],
       [2., 2.]])

In [56]:
np.ones((2, 2)) + np.ones((2, 2)) 

array([[2., 2.],
       [2., 2.]])

In [13]:
#Codigo 6
X = np.array([[1,2], [3, 4]])
Y = X[0, :]
Y[1] = 10
X

array([[ 1, 10],
       [ 3,  4]])

In [14]:
#Codigo 7
X = np.array([[1, 3], [11,10]])
np.mean(X[X > np.pi])

10.5

In [27]:
np.pi

3.141592653589793

In [28]:
#Codigo 8
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

pd.DataFrame(data=data, index=labels)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [ ]:
#Codigo 9
df = pd.DataFrame(data=data, index=labels)

df.shape




In [33]:
df['animal'].value_counts()

cat      4
dog      4
snake    2
Name: animal, dtype: int64

In [34]:
df['age'].mean()

3.4375

In [39]:
df.iloc[:, 3]

a    yes
b    yes
c     no
d    yes
e     no
f     no
g     no
h    yes
i     no
j     no
Name: priority, dtype: object

In [ ]:
df.sort_values(by='visits', ascending=False)

In [54]:
#Codigo 10
y_true = np.array([1., 2., 1.])
#y_pred = np.array([1.1, 1.98, 1.05 ])
y_pred = y_true

In [55]:
np.sqrt((y_true - y_pred)**2).mean()

0.0

In [47]:
0**2

0